# Generated by Django 5.0.6 on 2024-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
    ]
