# Generated by Django 5.0.6 on 2024-06-08 09:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_map', '0002_mission_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=4326)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_in_mission', to='military_map.mission')),
            ],
        ),
    ]
