# Generated by Django 5.0.6 on 2024-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_map', '0003_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
